version: '3.7'

services:

  karim_portfolio:
    container_name: karim_portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000