name: Continuous Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/karim_trabelsi .
      
    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/karim_trabelsi
      
    - name: Deploy
      run: |
        # Your deployment script or commands go here